# ── Dataset splits ──────────────────────────────────────────────────────────
dataset_size:   100000
val_split:      0.1
test_split:     0.1
val_size:       1000         # used by SyntheticDataset for on-the-fly val

seed:           42

# ── Filepaths for each split ───────────────────────────────────────────────
train_clean:    data/train_clean.npz
train_noisy:    data/train_noisy.npz
val_clean:      data/val_clean.npz
val_noisy:      data/val_noisy.npz
test_clean:     data/test_clean.npz
test_noisy:     data/test_noisy.npz

# ── Signal synthesis ─────────────────────────────────────────────────────────
# used by generate_synthetic.py, SyntheticDataset, and Gradio GUI
fs:             20e6          # sampling rate (Hz)
f0_range:       [1e6, 20e6]   # center frequency sweep (Hz)
cycles_range:   [1, 5]        # integer number of cycles per burst
noise_level_range: [0.01, 0.2]# σ_noise for Gaussian noise

# ── Training hyperparameters ────────────────────────────────────────────────
batch_size:     64
epochs:         200
lr_G:           5e-4
lr_D:           5e-4
gan_lambda:     5e-4         # weight for adversarial term in G loss

base_channels:  32
depths:         [1, 2, 4]

save_every:     1
checkpoint_dir: checkpoints

# ── Evaluation ───────────────────────────────────────────────────────────────
test_example_plot: test_denoise.png
